// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dapr/proto/internals/v1/service_invocation.proto

package internals

import (
	context "context"
	fmt "fmt"
	v1 "github.com/dapr/dapr/pkg/proto/common/v1"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Actor represents actor using actor_type and actor_id
type Actor struct {
	// Required. The type of actor.
	ActorType string `protobuf:"bytes,1,opt,name=actor_type,json=actorType,proto3" json:"actor_type,omitempty"`
	// Required. The ID of actor type (actor_type)
	ActorId              string   `protobuf:"bytes,2,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Actor) Reset()         { *m = Actor{} }
func (m *Actor) String() string { return proto.CompactTextString(m) }
func (*Actor) ProtoMessage()    {}
func (*Actor) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a1e51ba6ea480e4, []int{0}
}

func (m *Actor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Actor.Unmarshal(m, b)
}
func (m *Actor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Actor.Marshal(b, m, deterministic)
}
func (m *Actor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Actor.Merge(m, src)
}
func (m *Actor) XXX_Size() int {
	return xxx_messageInfo_Actor.Size(m)
}
func (m *Actor) XXX_DiscardUnknown() {
	xxx_messageInfo_Actor.DiscardUnknown(m)
}

var xxx_messageInfo_Actor proto.InternalMessageInfo

func (m *Actor) GetActorType() string {
	if m != nil {
		return m.ActorType
	}
	return ""
}

func (m *Actor) GetActorId() string {
	if m != nil {
		return m.ActorId
	}
	return ""
}

type InternalRegisterActorTimerRequest struct {
	ActorType            string   `protobuf:"bytes,1,opt,name=actor_type,json=actorType,proto3" json:"actor_type,omitempty"`
	ActorId              string   `protobuf:"bytes,2,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	DueTime              string   `protobuf:"bytes,4,opt,name=due_time,json=dueTime,proto3" json:"due_time,omitempty"`
	Period               string   `protobuf:"bytes,5,opt,name=period,proto3" json:"period,omitempty"`
	Callback             string   `protobuf:"bytes,6,opt,name=callback,proto3" json:"callback,omitempty"`
	Data                 *any.Any `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InternalRegisterActorTimerRequest) Reset()         { *m = InternalRegisterActorTimerRequest{} }
func (m *InternalRegisterActorTimerRequest) String() string { return proto.CompactTextString(m) }
func (*InternalRegisterActorTimerRequest) ProtoMessage()    {}
func (*InternalRegisterActorTimerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a1e51ba6ea480e4, []int{1}
}

func (m *InternalRegisterActorTimerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InternalRegisterActorTimerRequest.Unmarshal(m, b)
}
func (m *InternalRegisterActorTimerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InternalRegisterActorTimerRequest.Marshal(b, m, deterministic)
}
func (m *InternalRegisterActorTimerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InternalRegisterActorTimerRequest.Merge(m, src)
}
func (m *InternalRegisterActorTimerRequest) XXX_Size() int {
	return xxx_messageInfo_InternalRegisterActorTimerRequest.Size(m)
}
func (m *InternalRegisterActorTimerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InternalRegisterActorTimerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InternalRegisterActorTimerRequest proto.InternalMessageInfo

func (m *InternalRegisterActorTimerRequest) GetActorType() string {
	if m != nil {
		return m.ActorType
	}
	return ""
}

func (m *InternalRegisterActorTimerRequest) GetActorId() string {
	if m != nil {
		return m.ActorId
	}
	return ""
}

func (m *InternalRegisterActorTimerRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *InternalRegisterActorTimerRequest) GetDueTime() string {
	if m != nil {
		return m.DueTime
	}
	return ""
}

func (m *InternalRegisterActorTimerRequest) GetPeriod() string {
	if m != nil {
		return m.Period
	}
	return ""
}

func (m *InternalRegisterActorTimerRequest) GetCallback() string {
	if m != nil {
		return m.Callback
	}
	return ""
}

func (m *InternalRegisterActorTimerRequest) GetData() *any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

type InternalRegisterActorTimerResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InternalRegisterActorTimerResponse) Reset()         { *m = InternalRegisterActorTimerResponse{} }
func (m *InternalRegisterActorTimerResponse) String() string { return proto.CompactTextString(m) }
func (*InternalRegisterActorTimerResponse) ProtoMessage()    {}
func (*InternalRegisterActorTimerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a1e51ba6ea480e4, []int{2}
}

func (m *InternalRegisterActorTimerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InternalRegisterActorTimerResponse.Unmarshal(m, b)
}
func (m *InternalRegisterActorTimerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InternalRegisterActorTimerResponse.Marshal(b, m, deterministic)
}
func (m *InternalRegisterActorTimerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InternalRegisterActorTimerResponse.Merge(m, src)
}
func (m *InternalRegisterActorTimerResponse) XXX_Size() int {
	return xxx_messageInfo_InternalRegisterActorTimerResponse.Size(m)
}
func (m *InternalRegisterActorTimerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InternalRegisterActorTimerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InternalRegisterActorTimerResponse proto.InternalMessageInfo

// InternalInvokeRequest is the message to transfer caller's data to callee
// for service invocation. This includes callee's app id and caller's request data.
type InternalInvokeRequest struct {
	// Required. The version of Dapr runtime API.
	Ver APIVersion `protobuf:"varint,1,opt,name=ver,proto3,enum=dapr.proto.internals.v1.APIVersion" json:"ver,omitempty"`
	// Required. metadata holds caller's HTTP headers or gRPC metadata.
	Metadata map[string]*ListStringValue `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Required. message including caller's invocation request.
	Message *v1.InvokeRequest `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// Actor type and id. This field is used only for
	// actor service invocation.
	Actor                *Actor   `protobuf:"bytes,4,opt,name=actor,proto3" json:"actor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InternalInvokeRequest) Reset()         { *m = InternalInvokeRequest{} }
func (m *InternalInvokeRequest) String() string { return proto.CompactTextString(m) }
func (*InternalInvokeRequest) ProtoMessage()    {}
func (*InternalInvokeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a1e51ba6ea480e4, []int{3}
}

func (m *InternalInvokeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InternalInvokeRequest.Unmarshal(m, b)
}
func (m *InternalInvokeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InternalInvokeRequest.Marshal(b, m, deterministic)
}
func (m *InternalInvokeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InternalInvokeRequest.Merge(m, src)
}
func (m *InternalInvokeRequest) XXX_Size() int {
	return xxx_messageInfo_InternalInvokeRequest.Size(m)
}
func (m *InternalInvokeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InternalInvokeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InternalInvokeRequest proto.InternalMessageInfo

func (m *InternalInvokeRequest) GetVer() APIVersion {
	if m != nil {
		return m.Ver
	}
	return APIVersion_APIVERSION_UNSPECIFIED
}

func (m *InternalInvokeRequest) GetMetadata() map[string]*ListStringValue {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *InternalInvokeRequest) GetMessage() *v1.InvokeRequest {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *InternalInvokeRequest) GetActor() *Actor {
	if m != nil {
		return m.Actor
	}
	return nil
}

// InternalInvokeResponse is the message to transfer callee's response to caller
// for service invocation.
type InternalInvokeResponse struct {
	// Required. HTTP/gRPC status.
	Status *Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// Required. The app callback response headers.
	Headers map[string]*ListStringValue `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// App callback response trailers.
	// This will be used only for gRPC app callback
	Trailers map[string]*ListStringValue `protobuf:"bytes,3,rep,name=trailers,proto3" json:"trailers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Callee's invocation response message.
	Message              *v1.InvokeResponse `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *InternalInvokeResponse) Reset()         { *m = InternalInvokeResponse{} }
func (m *InternalInvokeResponse) String() string { return proto.CompactTextString(m) }
func (*InternalInvokeResponse) ProtoMessage()    {}
func (*InternalInvokeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a1e51ba6ea480e4, []int{4}
}

func (m *InternalInvokeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InternalInvokeResponse.Unmarshal(m, b)
}
func (m *InternalInvokeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InternalInvokeResponse.Marshal(b, m, deterministic)
}
func (m *InternalInvokeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InternalInvokeResponse.Merge(m, src)
}
func (m *InternalInvokeResponse) XXX_Size() int {
	return xxx_messageInfo_InternalInvokeResponse.Size(m)
}
func (m *InternalInvokeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InternalInvokeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InternalInvokeResponse proto.InternalMessageInfo

func (m *InternalInvokeResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *InternalInvokeResponse) GetHeaders() map[string]*ListStringValue {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *InternalInvokeResponse) GetTrailers() map[string]*ListStringValue {
	if m != nil {
		return m.Trailers
	}
	return nil
}

func (m *InternalInvokeResponse) GetMessage() *v1.InvokeResponse {
	if m != nil {
		return m.Message
	}
	return nil
}

// ListStringValue represents string value array
type ListStringValue struct {
	// The array of string.
	Values               []string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListStringValue) Reset()         { *m = ListStringValue{} }
func (m *ListStringValue) String() string { return proto.CompactTextString(m) }
func (*ListStringValue) ProtoMessage()    {}
func (*ListStringValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a1e51ba6ea480e4, []int{5}
}

func (m *ListStringValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListStringValue.Unmarshal(m, b)
}
func (m *ListStringValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListStringValue.Marshal(b, m, deterministic)
}
func (m *ListStringValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListStringValue.Merge(m, src)
}
func (m *ListStringValue) XXX_Size() int {
	return xxx_messageInfo_ListStringValue.Size(m)
}
func (m *ListStringValue) XXX_DiscardUnknown() {
	xxx_messageInfo_ListStringValue.DiscardUnknown(m)
}

var xxx_messageInfo_ListStringValue proto.InternalMessageInfo

func (m *ListStringValue) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

func init() {
	proto.RegisterType((*Actor)(nil), "dapr.proto.internals.v1.Actor")
	proto.RegisterType((*InternalRegisterActorTimerRequest)(nil), "dapr.proto.internals.v1.InternalRegisterActorTimerRequest")
	proto.RegisterType((*InternalRegisterActorTimerResponse)(nil), "dapr.proto.internals.v1.InternalRegisterActorTimerResponse")
	proto.RegisterType((*InternalInvokeRequest)(nil), "dapr.proto.internals.v1.InternalInvokeRequest")
	proto.RegisterMapType((map[string]*ListStringValue)(nil), "dapr.proto.internals.v1.InternalInvokeRequest.MetadataEntry")
	proto.RegisterType((*InternalInvokeResponse)(nil), "dapr.proto.internals.v1.InternalInvokeResponse")
	proto.RegisterMapType((map[string]*ListStringValue)(nil), "dapr.proto.internals.v1.InternalInvokeResponse.HeadersEntry")
	proto.RegisterMapType((map[string]*ListStringValue)(nil), "dapr.proto.internals.v1.InternalInvokeResponse.TrailersEntry")
	proto.RegisterType((*ListStringValue)(nil), "dapr.proto.internals.v1.ListStringValue")
}

func init() {
	proto.RegisterFile("dapr/proto/internals/v1/service_invocation.proto", fileDescriptor_6a1e51ba6ea480e4)
}

var fileDescriptor_6a1e51ba6ea480e4 = []byte{
	// 682 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0x5b, 0x6f, 0xd3, 0x4c,
	0x10, 0x6d, 0xee, 0xe9, 0xe4, 0xbb, 0xae, 0xa0, 0xa4, 0x46, 0x40, 0x6b, 0xfa, 0x10, 0x5e, 0x1c,
	0x1a, 0xa8, 0x8a, 0x0a, 0xad, 0x14, 0x50, 0x25, 0x22, 0x15, 0x09, 0xb9, 0x55, 0x05, 0xbc, 0x54,
	0x1b, 0x7b, 0x70, 0x97, 0xf8, 0xc6, 0x7a, 0x6d, 0x29, 0xef, 0xfc, 0x01, 0x7e, 0x21, 0xef, 0xfc,
	0x0a, 0xb4, 0xbb, 0xb6, 0xe9, 0xcd, 0x45, 0x41, 0x2a, 0x6f, 0xbb, 0x3e, 0x67, 0xce, 0xcc, 0xee,
	0x19, 0xcf, 0xc2, 0x63, 0x97, 0xc6, 0x7c, 0x18, 0xf3, 0x48, 0x44, 0x43, 0x16, 0x0a, 0xe4, 0x21,
	0xf5, 0x93, 0x61, 0xb6, 0x39, 0x4c, 0x90, 0x67, 0xcc, 0xc1, 0x13, 0x16, 0x66, 0x91, 0x43, 0x05,
	0x8b, 0x42, 0x4b, 0xb1, 0xc8, 0x1d, 0x19, 0xa1, 0xd7, 0x56, 0x19, 0x61, 0x65, 0x9b, 0xc6, 0xfa,
	0x19, 0x29, 0x27, 0x0a, 0x82, 0x28, 0x94, 0x3a, 0x7a, 0xa5, 0xf9, 0xc6, 0xa0, 0x2a, 0x1b, 0x8d,
	0x59, 0x86, 0x3c, 0x29, 0xb3, 0x18, 0x1b, 0x95, 0x75, 0x09, 0x2a, 0xd2, 0x24, 0x67, 0xad, 0x7a,
	0x51, 0xe4, 0xf9, 0xa8, 0x79, 0xd3, 0xf4, 0xe3, 0x90, 0x86, 0xf3, 0x1c, 0xba, 0x7b, 0x11, 0xc2,
	0x20, 0x16, 0x39, 0x68, 0x8e, 0xa1, 0x35, 0x76, 0x44, 0xc4, 0xc9, 0x3d, 0x00, 0x2a, 0x17, 0x27,
	0x62, 0x1e, 0x63, 0xbf, 0xb6, 0x56, 0x1b, 0x2c, 0xdb, 0xcb, 0xea, 0xcb, 0xd1, 0x3c, 0x46, 0xb2,
	0x0a, 0x5d, 0x0d, 0x33, 0xb7, 0x5f, 0x57, 0x60, 0x47, 0xed, 0x27, 0xae, 0xf9, 0xbd, 0x06, 0xeb,
	0x93, 0xbc, 0x30, 0x1b, 0x3d, 0x96, 0x08, 0xe4, 0x4a, 0xf3, 0x88, 0x05, 0xc8, 0x6d, 0xfc, 0x9c,
	0x62, 0x22, 0x7e, 0x5f, 0x9f, 0x10, 0x68, 0x86, 0x34, 0xc0, 0x7e, 0x43, 0x7d, 0x56, 0x6b, 0x49,
	0x77, 0x53, 0x3c, 0x11, 0x2c, 0xc0, 0x7e, 0x53, 0xd3, 0xdd, 0x14, 0x65, 0x42, 0xb2, 0x02, 0xed,
	0x18, 0x39, 0x8b, 0xdc, 0x7e, 0x4b, 0x01, 0xf9, 0x8e, 0x18, 0xd0, 0x75, 0xa8, 0xef, 0x4f, 0xa9,
	0x33, 0xeb, 0xb7, 0x15, 0x52, 0xee, 0xc9, 0x00, 0x9a, 0x2e, 0x15, 0xb4, 0xdf, 0x59, 0xab, 0x0d,
	0x7a, 0xa3, 0x5b, 0x96, 0xbe, 0x31, 0xab, 0xb8, 0x31, 0x6b, 0x1c, 0xce, 0x6d, 0xc5, 0x30, 0x37,
	0xc0, 0xbc, 0xee, 0xac, 0x49, 0x1c, 0x85, 0x09, 0x9a, 0x5f, 0x1a, 0x70, 0xbb, 0xa0, 0x4d, 0xc2,
	0x2c, 0x9a, 0x61, 0x71, 0x0d, 0x5b, 0xd0, 0xc8, 0x90, 0xab, 0xf3, 0xff, 0x33, 0x7a, 0x68, 0x55,
	0x74, 0x90, 0x35, 0x7e, 0x3b, 0x39, 0xd6, 0x5d, 0x60, 0x4b, 0x3e, 0x79, 0x07, 0xdd, 0x00, 0x05,
	0x55, 0x45, 0xd6, 0xd7, 0x1a, 0x83, 0xde, 0xe8, 0x45, 0x65, 0xec, 0x95, 0x89, 0xad, 0x37, 0x79,
	0xf8, 0x7e, 0x28, 0xf8, 0xdc, 0x2e, 0xd5, 0xc8, 0x2e, 0x74, 0x02, 0x4c, 0x12, 0xea, 0xe9, 0x0b,
	0xee, 0x9d, 0x2f, 0x2a, 0xef, 0x59, 0xa5, 0x7a, 0x46, 0xcd, 0x2e, 0x62, 0xc8, 0x53, 0x68, 0x29,
	0x9f, 0x94, 0x0b, 0xbd, 0xd1, 0xfd, 0xea, 0x13, 0x49, 0x96, 0xad, 0xc9, 0x06, 0xc2, 0xdf, 0xe7,
	0xea, 0x21, 0xff, 0x41, 0x63, 0x86, 0xf3, 0xbc, 0x2d, 0xe4, 0x92, 0xec, 0x41, 0x2b, 0xa3, 0x7e,
	0x8a, 0xaa, 0x1b, 0x7a, 0xa3, 0x41, 0xa5, 0xf0, 0x01, 0x4b, 0xc4, 0xa1, 0xe0, 0x2c, 0xf4, 0x8e,
	0x25, 0xdf, 0xd6, 0x61, 0x3b, 0xf5, 0x67, 0x35, 0xf3, 0x6b, 0x13, 0x56, 0x2e, 0xde, 0x86, 0x76,
	0x88, 0x6c, 0x43, 0x5b, 0xff, 0x3f, 0x2a, 0x67, 0x6f, 0xf4, 0xa0, 0x52, 0xff, 0x50, 0xd1, 0xec,
	0x9c, 0x4e, 0x8e, 0xa1, 0x73, 0x8a, 0xd4, 0x45, 0x9e, 0x2c, 0x6c, 0x84, 0x4e, 0x6d, 0xbd, 0xd6,
	0xe1, 0xda, 0x88, 0x42, 0x8c, 0xbc, 0x87, 0xae, 0xe0, 0x94, 0xf9, 0x52, 0xb8, 0xa1, 0x84, 0x77,
	0x17, 0x15, 0x3e, 0xca, 0xe3, 0x73, 0x8b, 0x0b, 0x39, 0xb2, 0xf7, 0xd3, 0x62, 0xed, 0xd2, 0xc6,
	0xf5, 0x16, 0x6b, 0xb9, 0xd2, 0x63, 0xc3, 0x85, 0xbf, 0xce, 0xd6, 0x7c, 0x33, 0x66, 0xc9, 0x9e,
	0x38, 0x77, 0x80, 0x1b, 0xea, 0x89, 0x47, 0xf0, 0xef, 0x05, 0x54, 0x4e, 0x0c, 0x85, 0xcb, 0x5e,
	0x68, 0xc8, 0x89, 0xa1, 0x77, 0xa3, 0x6f, 0x75, 0xf8, 0xff, 0x50, 0x0f, 0xff, 0x49, 0x39, 0xfb,
	0x49, 0x08, 0xcb, 0xaf, 0xa8, 0xef, 0xeb, 0xa9, 0x69, 0x2d, 0xf6, 0x17, 0x1a, 0xc3, 0x05, 0x3d,
	0x35, 0x97, 0x8a, 0x7c, 0x07, 0x91, 0x43, 0xfd, 0x3f, 0x91, 0xef, 0x13, 0x90, 0xcb, 0x93, 0x8d,
	0xec, 0xfc, 0x52, 0xa8, 0x72, 0xf4, 0x1b, 0x2b, 0x97, 0xe6, 0xe9, 0xbe, 0x7c, 0x81, 0xcc, 0xa5,
	0x97, 0xdb, 0x1f, 0xb6, 0x3c, 0x26, 0x4e, 0xd3, 0xa9, 0xec, 0xc2, 0xa1, 0x7a, 0xe8, 0xf4, 0x6b,
	0x37, 0xf3, 0xae, 0x78, 0xf1, 0x9e, 0x97, 0x9b, 0x69, 0x5b, 0xa1, 0x4f, 0x7e, 0x04, 0x00, 0x00,
	0xff, 0xff, 0xde, 0x7e, 0xc0, 0xec, 0xb5, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ServiceInvocationClient is the client API for ServiceInvocation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServiceInvocationClient interface {
	// Invokes a method of the specific actor.
	CallActor(ctx context.Context, in *InternalInvokeRequest, opts ...grpc.CallOption) (*InternalInvokeResponse, error)
	// Invokes a method of the specific service.
	CallLocal(ctx context.Context, in *InternalInvokeRequest, opts ...grpc.CallOption) (*InternalInvokeResponse, error)
	RegisterActorTimer(ctx context.Context, in *InternalRegisterActorTimerRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type serviceInvocationClient struct {
	cc *grpc.ClientConn
}

func NewServiceInvocationClient(cc *grpc.ClientConn) ServiceInvocationClient {
	return &serviceInvocationClient{cc}
}

func (c *serviceInvocationClient) CallActor(ctx context.Context, in *InternalInvokeRequest, opts ...grpc.CallOption) (*InternalInvokeResponse, error) {
	out := new(InternalInvokeResponse)
	err := c.cc.Invoke(ctx, "/dapr.proto.internals.v1.ServiceInvocation/CallActor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceInvocationClient) CallLocal(ctx context.Context, in *InternalInvokeRequest, opts ...grpc.CallOption) (*InternalInvokeResponse, error) {
	out := new(InternalInvokeResponse)
	err := c.cc.Invoke(ctx, "/dapr.proto.internals.v1.ServiceInvocation/CallLocal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceInvocationClient) RegisterActorTimer(ctx context.Context, in *InternalRegisterActorTimerRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/dapr.proto.internals.v1.ServiceInvocation/RegisterActorTimer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceInvocationServer is the server API for ServiceInvocation service.
type ServiceInvocationServer interface {
	// Invokes a method of the specific actor.
	CallActor(context.Context, *InternalInvokeRequest) (*InternalInvokeResponse, error)
	// Invokes a method of the specific service.
	CallLocal(context.Context, *InternalInvokeRequest) (*InternalInvokeResponse, error)
	RegisterActorTimer(context.Context, *InternalRegisterActorTimerRequest) (*empty.Empty, error)
}

// UnimplementedServiceInvocationServer can be embedded to have forward compatible implementations.
type UnimplementedServiceInvocationServer struct {
}

func (*UnimplementedServiceInvocationServer) CallActor(ctx context.Context, req *InternalInvokeRequest) (*InternalInvokeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CallActor not implemented")
}
func (*UnimplementedServiceInvocationServer) CallLocal(ctx context.Context, req *InternalInvokeRequest) (*InternalInvokeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CallLocal not implemented")
}
func (*UnimplementedServiceInvocationServer) RegisterActorTimer(ctx context.Context, req *InternalRegisterActorTimerRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterActorTimer not implemented")
}

func RegisterServiceInvocationServer(s *grpc.Server, srv ServiceInvocationServer) {
	s.RegisterService(&_ServiceInvocation_serviceDesc, srv)
}

func _ServiceInvocation_CallActor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InternalInvokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceInvocationServer).CallActor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dapr.proto.internals.v1.ServiceInvocation/CallActor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceInvocationServer).CallActor(ctx, req.(*InternalInvokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceInvocation_CallLocal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InternalInvokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceInvocationServer).CallLocal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dapr.proto.internals.v1.ServiceInvocation/CallLocal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceInvocationServer).CallLocal(ctx, req.(*InternalInvokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceInvocation_RegisterActorTimer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InternalRegisterActorTimerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceInvocationServer).RegisterActorTimer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dapr.proto.internals.v1.ServiceInvocation/RegisterActorTimer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceInvocationServer).RegisterActorTimer(ctx, req.(*InternalRegisterActorTimerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ServiceInvocation_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dapr.proto.internals.v1.ServiceInvocation",
	HandlerType: (*ServiceInvocationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CallActor",
			Handler:    _ServiceInvocation_CallActor_Handler,
		},
		{
			MethodName: "CallLocal",
			Handler:    _ServiceInvocation_CallLocal_Handler,
		},
		{
			MethodName: "RegisterActorTimer",
			Handler:    _ServiceInvocation_RegisterActorTimer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dapr/proto/internals/v1/service_invocation.proto",
}
